### ISSUE TITLE
Big changes welcome?

### ISSUE THREAD

**Issue by TimMensch** [grimmdude/MidiPlayerJS#10]
I'm using MidiPlayerJS in a project I'm working on, and I found it was difficult to integrate with TypeScript and RollupJS as-is. I also had some problems getting it to build at all on Windows. 

So I ended up making my own fork and restructuring it. I pulled in `gulp` and made files properly `require` each other, among other things.

I'm reluctant to send a pull-request with so many structural changes without asking first, so I'm asking, since I would like to offer the improvements to the main project.  The branch with the changes is here: 

https://github.com/TimMensch/MidiPlayerJS/tree/tim

In addition to the initial changes, I also made the code work on Safari (which included some potential optimizations), fixed the Program Change event to actually include the new value, and a few other things.

I'm happy to submit the whole set of changes as a pull request, but I don't have the time to break things down into smaller pull requests if you don't want it all.

Let me know.

**Comment by grimmdude** [comment]
Hi @TimMensch,

Thanks for very much for sending this over, improvements are always welcome.  I will take a look at the changes a little later and get back to you.

For my info, what issues were you having integrating with your code as is?  Guessing the build issues on Windows had to do with the Unix like commands?

-Garrett

**Comment by TimMensch** [comment]
The main build issues were due to the Bash commands, yes. Even though I use Bash and run `npm` and `yarn` from Bash, they must be spawning a `cmd` or `PowerShell` shell to execute the command lines. And instead of trying to create something custom that will work on Windows, Linux, and Mac, I went to the standard `gulp` which I believe will Just Work.

But there were other issues. I'm using Rollup and its ES6 includes. Pulling in files that really were intended to be concatenated together in order to work at all was confusing Rollup. And once I changed the code to use proper `require`s throughout, I needed to change the Node build as well. It occurs to me that it could have been changed to be a tree of Babel-ified files instead of using Browserify to package the files, but the latter was my first idea, and so I ran with it.

I also needed the package to be UMD-wrapped for the browser: The Browserify export by default seems to assume it's the _only_ export, and instead of "real" exports, it exports a `require` command, and it wants client code to `require` the modules directly. Using Rollup and TypeScript I could _potentially_ have made something like that work, but it felt awkward to have some `require` commands be executed at runtime when the rest were flattened at build time by Rollup. Possible, but it felt wrong, and potentially fragile, especially if something else wanted to define a global `require`. At a minimum it would have been firing linting errors any time I `require`d your code, and I think it also would have broken the type declarations entirely.

Given I changed to a UMD package, it does like mean that this will break compatibility with current users of `midi-player-js`, which will be expecting a global `require` instead of a global `MidiPlayerJS`. UMD is really the standard way of interfacing with browsers, though, so I think it's better than the Browserify global `require`. Maybe a major version number bump would be called for?

**Comment by TimMensch** [comment]
To help simplify your review, I created a pull request that only has the relevant changes. 

I did include .vscode config files that would help users build and debug the code from within VS Code.

**Comment by grimmdude** [comment]
Hi @TimMensch,

Your changes are good and merged, thanks very much.  I admit I'm not very well versed with browserify and UMD best practices so this helps a lot.  Having `MidiPlayer` as a global variable in the browser was my initial goal, but I think I conceded to export that `require` function since that's how I got it to work at the time.

I've updated the demo file to use the new global variable and published `2.0.0` to npm.  Feel free to PR any other changes you may have moving forward, thanks!

-Garrett
