### ISSUE TITLE
Typescript counterpart

### ISSUE THREAD

**Issue by tjvg91** [grimmdude/MidiPlayerJS#12]
Is there a typescript counterpart for this? I plan to embed this in an Angular 4 project but I get this error:

`ReferenceError: require is not defined`

**Comment by grimmdude** [comment]
I'm not too familiar with TypeScript.  @TimMensch do you have any insight to this?

**Comment by gciluffo** [comment]
@tjvg91  If your using typescript you can just do `import * as vexflow from 'vexflow';`

**Comment by tjvg91** [comment]
thanks @gciluffo but I get this error this time:
`Error: Cannot find module 'fs'`

**Comment by TimMensch** [comment]
Module 'fs' doesn't exist on the browser. You can't use the file API in the browser.

**Comment by tjvg91** [comment]
How can i do so? @TimMensch

**Comment by TimMensch** [comment]
Please don't ask questions until you have done a minimum of research yourself. The bare minimum in this case is reading the docs:

http://grimmdude.com/MidiPlayerJS/docs/Player.html#loadFile

See how it says loadFile() is Node.js only? That means it won't work in the browser. Look at the other options and choose one.
