### ISSUE TITLE
Getting Key and Time Signatures, Transposition

### ISSUE THREAD

**Issue by tjvg91** [grimmdude/MidiPlayerJS#17]
How do you get the key and time signatures? Can I transpose to a different key?

**Comment by grimmdude** [comment]
Hi @tjvg91,

Currently key & time signatures aren't implemented, I will work on that as soon as I get a chance.  As far as transposing, you can handle this at your application level.  Here's an example:

```js
var MidiPlayer = require('midi-player-js');

// Initialize player and register event handler
var Player = new MidiPlayer.Player(function(event) {
	switch (event.name) {
		case 'Note on':
			// This is a note event, you can transpose here as needed.
			// Here's an example of transposing up a half step
                        // You would assumably use this information to trigger an audio event.
			console.log(event.noteNumber + 1);
			break;
	}
});

// Load a MIDI file
Player.loadFile('./test.mid');
Player.play();
```

**Comment by grimmdude** [comment]
I just added support for key signatures and time signatures in 2.0.2.  Let me know if you have any issues,

-Garrett

**Comment by tjvg91** [comment]
Thanks. Will try it out. Is it in npm too?

**Comment by grimmdude** [comment]
Yep, it's updated in npm.
