### ISSUE TITLE
Package on npm missing browser/ directory for version = 2.0.2

### ISSUE THREAD

**Issue by RakanNimer** [grimmdude/MidiPlayerJS#20]
Hey !

Thanks for the great work on MidiPlayerJS, it's my go-to library when prototyping music code 😃.

I noticed that in version 2.0.2 the browser folder is not being uploaded to npm.
https://unpkg.com/midi-player-js@2.0.2/

Cheers !

**Comment by RakanNimer** [comment]
Related to #19. 

Workaround : 
``` npm i --save midi-player-js@2.0.1 ```

**Comment by grimmdude** [comment]
Hi @RakanNimer,

Ah sorry about that, just published `2.0.3` which should contain the `browser/` directory again.

-Garrett
