### ISSUE TITLE
Add more musical instruments

### ISSUE THREAD

**Issue by surikov** [grimmdude/MidiPlayerJS#21]
Add more musical instruments from WebAudioFonts.

It includes samples from Fluid, General User GS etc. Pianos, guitars, Fx, about 2000 instruments and drums.
See example at 
https://surikov.github.io/webaudiofont/examples/dynamic.html

**Comment by grimmdude** [comment]
Hi @surikov,

Thanks for the post.  This library provides only the player engine and doesn't deal with sound fonts directly.

However, if you would like to create an example MIDI player using `MidiPlayerJS` using your sound font library I would be happy to add a link to it in this library's readme.

-Garrett
