### ISSUE TITLE
Using in browser, require is not finding midi-player-js

### ISSUE THREAD

**Issue by fornof** [grimmdude/MidiPlayerJS#23]
```html
<script src="node_modules/midi-player-js/browser/midiplayer.js" type="text/javascript"></script>
```
```
Error: Uncaught (in promise) Error: Cannot find module 'midi-player-js'

when trying default script:
```
```js
var MidiPlayer = require('midi-player-js');

// Initialize player and register event handler
var Player = new MidiPlayer.Player(function(event) {
        console.log(event);
});

// Load a MIDI file
Player.loadFile(url);
Player.play(); 
```
It is probably something simple I'm doing wrong.

**Comment by grimmdude** [comment]
Hi @fornof,

Thanks for the message.  With using the built browser file in this library you should be able to access the global `MidiPlayer` class without using `require()`.

```js
var MidiPlayer = MidiPlayer;
```

Let me know if you have any issues with that.

-Garrett

**Comment by grimmdude** [comment]
You may also run into obstacles when using `Player.loadFile()` in the browser.  Check out the source on the demo for a working example https://grimmdude.com/MidiPlayerJS/demo/js/app.js

-Garrett

**Comment by fornof** [comment]
I used the example and have it showing note on and note off in the console. However no notes are playing because the Soundfont /instrument is not found. Its another issue, I'll read the documentation some more and open up another issue if I cannot figure it out. Thank you so much for your help!

**Comment by grimmdude** [comment]
@fornof, noticed you re-opened this issue.  Are you still have trouble?

-Garrett

**Comment by fornof** [comment]
I was going to reply, then followed your link to get notes to turn off when even off was pressed. 
https://github.com/danigb/soundfont-player/issues/59 
It works, I just never closed/finished replying to this issue. thanks for following up!
