### ISSUE TITLE
Player.getEvents typings incorrect

### ISSUE THREAD

**Issue by xeoneux** [grimmdude/MidiPlayerJS#24]
`Player.getEvents` method does not return an array of events, but an array of array of events.

**Comment by grimmdude** [comment]
Hi @xeoneux,

Thanks for your message.  Correct, `Player.getEvents()` returns an array of tracks each of which contains an array of events for that track.

-Garrett

**Comment by xeoneux** [comment]
There are a few other issues with the typings. Would you accept a PR if I convert the code into TypeScript?

**Comment by xeoneux** [comment]
It won't change the way how the library is currently used.

It'd remove dependency on gulp and babel and would also improve the developer experience.
