### ISSUE TITLE
Simultaneous Notes Don't Play At The Same Time

### ISSUE THREAD

**Issue by FireController1847** [grimmdude/MidiPlayerJS#25]
I've attached a test midi file to this issue. When running this, you can see that it only plays the notes slowly down the entire piano, versus all of them at once.

If you play the file using this module, all the notes do not play at once. If you play it using a third-party midi player (or look at my FL studio file even though I didn't upload it), it's two giant smashes all at once.

[test.zip](https://github.com/grimmdude/MidiPlayerJS/files/1930688/test.zip)

**Comment by grimmdude** [comment]
Hi @FireController1847,

I believe this is just a limitation of the web browser and the fact that there are so many notes playing at the same time.  In MIDI everything is sequential, so the browser is playing the notes as fast as possible.  

-Garrett

**Comment by FireController1847** [comment]
I did not test this in a browser, I tested it in a Node.js process. All other midi players do not have this issue, this is the only one I've found.

**Comment by grimmdude** [comment]
Hi @FireController1847 

I see, well could be the same limitation in the Node runtime.  I'm guessing the other players your referring to are ones built in lower level languages like C.  I'll see if I can find any room for optimization though.

-Garrett

**Comment by FireController1847** [comment]
Alright, glad to hear. I've made a kind-of-working midi players using the midievents and midifile modules I've emailed you with, which did not have this issue so it is not a limitation of Node.js or a browser.

**Comment by ledlamp** [comment]
This is because of the implementation used: it uses a single 5ms interval to run all the timing. So presumably, notes within 5ms are unable to play faster than that. You can fix this by maximizing the interval (aka "sample rate") like so:
```
Player.sampleRate = 0;
```
This pretty much solves the problem. It can still lag at extremely dense clusters of notes, but I think that's just a limitation of this method. To solve that, I think it would need to use setTimeout for each event.

**Comment by FireController1847** [comment]
If I recall, that helped a lot, but this module does overall have a fatal flaw of relying on `setInterval` in a loop instead of `setTimeout` on note times. Hopefully, through the emails, I'll be able to work on learning midi and possibly PR in the future to fix this flaw.

**Comment by grimmdude** [comment]
@FireController1847 closing this out for now.  Been trying different ideas for reducing the latency between many simultaneous event firing but haven't really found much improvement.  Let me know if you have any other ideas.  Thanks,

-Garrett

**Comment by FireController1847** [comment]
Haha, alright, thanks. It's alright, I've moved on from my midi phase anyways :)

**Comment by TheAlienDrew** [comment]
Shouldn't it be set to 1ms??? That's the official midi spec for sample rate.

**Comment by TheAlienDrew** [comment]
Ah... noticed an issue with having it set to 1 (even though that's the standard), it looks like it may miss endOfFile events.
