### ISSUE TITLE
This MIDI does not work

### ISSUE THREAD

**Issue by ledlamp** [grimmdude/MidiPlayerJS#29]
https://files.catbox.moe/6l2uuw.mid
When trying to play this MIDI, nothing happens. The event listener is never called. Player.events is empty.
And I notice Player.tick is an extremely high number.

**Comment by FunkeMT** [comment]
If I try to open and decode your MIDI file with [MidiAndMusicXmlPlayer](http://www.programfabriken.com) I get this error:

```
Assert Failed: Illegal Channel Number specified 0 in index:0037
```

Well, I think your MIDI file is corrupted rather than there is an error in the MidiPlayerJS.

**Comment by ledlamp** [comment]
Huh, I guess it is an invalid MIDI. But all the other MIDI players I've used play the file fine, so I think this player could be made to handle the problem.

**Comment by grimmdude** [comment]
Hi @ledlamp ,

I recently pushed some changes in 2.0.8 which should fix this.

-Garrett
