### ISSUE TITLE
getSongTimeRemaining() always showing end of song

### ISSUE THREAD

**Issue by JudeOsborn** [grimmdude/MidiPlayerJS#30]
While playing a song getSongTimeRemaining() always seems to show the maximum song time. So I have no way of knowing when a song is over. Seems to be a bug?

Or is there another way of knowing a songs progress? I could do my own timer and keep track of the tempo, etc., but that's redundant.

**Comment by grimmdude** [comment]
Thanks for the message.  Sounds like you were able to resolve?
