### ISSUE TITLE
Detect corrupted files

### ISSUE THREAD

**Issue by Toxiapo** [grimmdude/MidiPlayerJS#31]
My app would just freeze and I had to force quit it if I try to play a corrupted MIDI file, is there a way for me to detect if the file is even playable or if it's a valid midi file?

**Comment by grimmdude** [comment]
Hi @Toxiapo,

Thanks for your message.  If you could provide an example of the corrupted file we can try to detect similar issues in other files before attempting to play.

-Garrett

**Comment by Toxiapo** [comment]
This is the file I am testing with. https://transfer.sh/dmwjs/normal-battle.mid

I have this file in my server along with others. Instead of me downloading a file to my computer, I am using a GET request to get the blob response then convert it to base64 and have it loaded to the loadDataUri function.

The other files are working fine except with this one.

**Comment by grimmdude** [comment]
Hi @Toxiapo ,

I recently pushed some updates to 2.0.8 that I think might solve this problem for you.  The MIDI file you posted is no longer available so I can't really check, but let me know if so.

-Garrett
