### ISSUE TITLE
Some midis will create an Infinite loop when loading file

### ISSUE THREAD

**Issue by BopItFreak** [grimmdude/MidiPlayerJS#33]
Some midis, which are valid on other players, seem to create an Infinite loop when loading the file. 
one of these midis is this: https://cdn.discordapp.com/attachments/360985607209484290/477205561469829121/9934.mid

please fix this.

**Comment by Vistril** [comment]
It happens for me when you play a song without stopping the player first. Even though I call player.stop() the first thing when 'endOfFile' fires, it still doesn't stop and cpu usage spikes. I tried to use async to fix it but as Lamp said `anything with  async never completes.` So, what gives?

**Comment by lexcast** [comment]
The bug is here: https://github.com/grimmdude/MidiPlayerJS/blob/master/src/player.js#L428
should be `>=`:
```js
endOfFile() {
	if (this.isPlaying()) {
		return this.totalTicks - this.tick <= 0;
	}

	return this.bytesProcessed() >= this.buffer.length;
}
```
