### ISSUE TITLE
Time signature incorrectly calculated.

### ISSUE THREAD

**Issue by hrbaer** [grimmdude/MidiPlayerJS#34]
Please note that the denominator of the time signature should be a power of two, not the square.
Change line 230 in file "track.js" to: 

`eventJson.timeSignature = "" + eventJson.data[0] + "/" + Math.pow(2, eventJson.data[1]);`

Best regards

**Comment by grimmdude** [comment]
Hi @hrbaer,

Thanks for bringing this to my attention, just pushed 2.0.4 with fix.

-Garrett
