### ISSUE TITLE
question:how to compile to single file

### ISSUE THREAD

**Issue by annopnod** [grimmdude/MidiPlayerJS#35]
question:how to compile src to single file uncompress mode

**Comment by Otto-AA** [comment]
_Disclaimer: I'm no developer of this project_

Clone this repository and then running `npm run build` will create the directories _browser_ and _module_. In these folders, there are the compiled files (compressed and uncompressed).

**Comment by grimmdude** [comment]
Easiest way would be to use `npm install midi-player-js` to grab the latest release which will already be built for you.

-Garrett

**Comment by annopnod** [comment]
thank you
