### ISSUE TITLE
Not working on Safari iOS

### ISSUE THREAD

**Issue by AndresMendozaDev** [grimmdude/MidiPlayerJS#36]
Hi; 

The player works fine on Chrome for Windows 10; it loads the instruments and start playing.

It doesn't work on Safari for iOS; on the debugger I see the data (I'm printing current note) but I can't hear any sound.

Notes: 
- I'm using your demo; I'm forcing it to start playing after a user input.
- On the network panel on the debugger, I see it loads the same instrument always: accoustic_guitar_nylon

I would appreciate any help!

**Comment by TheAlienDrew** [comment]
Seeing what your problem is... it doesn't look like a problem with the MIDI player, rather it might be a problem with the soundfont library grimmdude is using to play audio to each note. https://github.com/danigb/soundfont-player
