### ISSUE TITLE
Problem with load and parse data

### ISSUE THREAD

**Issue by laven2** [grimmdude/MidiPlayerJS#37]
When i load midi file with loadArrayBuffer i have 530 events of 'Controller change' (sustain)
but when i load my file with https://github.com/Tonejs/MidiConvert i have 700 events of 'Controller change'
and 530 events it's wrong logic, 700 is true, what could it be?

**Comment by grimmdude** [comment]
Hi Valery,

Thanks for your message.  Could you provide the MIDI file in question please?

-Garrett

**Comment by grimmdude** [comment]
Hi @laven2,

Implemented sysex events in 2.0.9 which I _think_ should fix this for you.

-Garrett
