### ISSUE TITLE
“browser” folder - browserify fails

### ISSUE THREAD

**Issue by jeniffer9** [grimmdude/MidiPlayerJS#38]
Hi!

I have just a small question. In the index.html file you add a script with src=“browser/midiplayer.min.js“ but I cannot find the browser directory at all... how does this work?
Also everytime I try to browserify midi-player-js, it fails with an error saying that it cannot find the files in the ‘browser’ folder because it doesn’t exist...

I would be very happy if someone could explain that to me.
Thanks!

**Comment by grimmdude** [comment]
HI @jeniffer9,

Thanks for your message.  The `/browser` directory is only available in the built package which can be installed using npm:

```npm install midi-player-js```

Let me know if you still have questions,

-Garrett

**Comment by jeniffer9** [comment]
Thanks for your quick answer!

So now I tried `npm install midi-player-js` in `/npm_modules` of my project.
However browserifying the module still doesn't work since it is looking for the `./player` file inside `/browser` but the only two files located in `/browser` are `midiplayer.js` and `midiplayer.min.js`.

Is that normal?

-Jeniffer

**Comment by grimmdude** [comment]
HI Jeniffer,

The files in `/browser` are already browserified.  You should be able to just use the `midiplayer.min.js` (minified version) in a script tag within your HTML.  Does that answer your question?

-Garrett

**Comment by jeniffer9** [comment]
Hi Garrett,

Yes, I think I got it now!
Thank you very much! :)

Best,
Jeniffer
