### ISSUE TITLE
can you add getSongPercent feature?

### ISSUE THREAD

**Issue by kazukazu123123** [grimmdude/MidiPlayerJS#43]
can you add Reverse version of getSongPercentRemaining?
sorry my bad english because i from japan!

**Comment by grimmdude** [comment]
Hi @kazukazu123123,

Thanks for your message.  I will make a note to add this, but in the meantime you should be able to get current current song percent like this:
```js
var currentSongPercent = 100 - Player.getSongPercentRemaining();
```

**Comment by kazukazu123123** [comment]
Okay Thanks!

**Comment by kazukazu123123** [comment]
it's worked thanks!
