### ISSUE TITLE
setStartTime undefined

### ISSUE THREAD

**Issue by Mourad95** [grimmdude/MidiPlayerJS#46]
Hello, 
 
When I do midiPlayer.setStartime(4) he say that is undefined. I don't no why, because when I log midiPlayer.setStartime it print:
 midiPlayer.setStartTime :   ƒ setStartTime(startTime) {
            this.startTime = startTime;
          }.
When I log the methode he print : undefined...

Thanks for your help.

**Comment by grimmdude** [comment]
Hi @Mourad95,

Thanks for your message.  `setStartTime()` doesn't return anything which is why you're seeing `undefined` in console; it just sets the `startTime` property in the player.  Did you need it to return something?

-Garrett

**Comment by Mourad95** [comment]
Thanks a lot for you answer.
I don't need to return something, but setStartTime(4) does not work.
Play() method work...
I don't know why.
Did I need to get setTime(4) and after Play()?

I have an other question pleas... How can get notes number at each time?
Thanks for your help
*Cordialement,*

*Mr AUMAR Mourad.*



Le dim. 3 mars 2019 à 21:59, Garrett Grimm <notifications@github.com> a
écrit :

**Comment by grimmdude** [comment]
Hi @Mourad95,

`setStartTime()` requires a UTC timestamp, perhaps that's why it's not working as expected for you.

If you want to skip to a particular point in the playback, using `skipToTick()` or `skipToPercent()` might work better.

-Garrett
