### ISSUE TITLE
Browserify complaining

### ISSUE THREAD

**Issue by b3u** [grimmdude/MidiPlayerJS#47]
I'm trying to use MidiPlayerJS in the browser. I installed it as an npm module, but when I use browserify to compile it, it gives me the following error:
```sh
Error: Cannot find module './utils' from 'C:\Users\bgree\Documents\chordy\node_modules\midi-player-js\browser'
...
```
I checked the module, and, sure enough, it's requiring a module (utils) which doesn't exist. Please advise.

**Comment by grimmdude** [comment]
Hi @b3u,

`browser/midiplayer.js` is meant to be used in the browser via script tag as is so guessing why you're seeing that issue.  Try using the main entry point for the module; `build/index.js`.

-Garrett

**Comment by b3u** [comment]
Thanks
