### ISSUE TITLE
Sound goes really weird when the song goes on

### ISSUE THREAD

**Issue by Josema23** [grimmdude/MidiPlayerJS#50]
I've been trying the library on my computer and I realized that, when the song goes on, the sound gets really weird. It happens to in one of the demos that are available on the docs. Does anybody know why? @grimmdude

**Comment by grimmdude** [comment]
Hi @Josema23,

Which demo is giving you trouble?  Which browser are you using?  Thanks,

-Garrett

**Comment by Josema23** [comment]
This is the Demo which is giving me trouble:
http://grimmdude.com/MidiPlayerJS/
The sound starts in a good way, but when it goes to the middle it starts sounding really weird

**Comment by KristerV** [comment]
yeah same here. Arch Linux, Firefox. Chromium works fine.

**Comment by grimmdude** [comment]
Closing this for now as the audio part of the demo is separate from MidiPlayerJS.
