### ISSUE TITLE
[BUG] File loading broken

### ISSUE THREAD

**Issue by TheAlienDrew** [grimmdude/MidiPlayerJS#57]
Whenever I try to load this file ([500 Miles.mid](https://anonymousfiles.io/QE5OfeTF/)), it completely crashes the script using your library.

**Comment by grimmdude** [comment]
Hey @TheAlienDrew ,

It looks like this file has a total byte length of 38,177, however the MIDI chunks only seem to add up to 38,176 so the player is having trouble reaching the end of file when parsing.  I'm trying to track down where that extra byte is coming from so perhaps we can catch this issue and correct for it...

-Garrett

**Comment by grimmdude** [comment]
Ah found it, looks like there's a straggling 0x0a byte at the end of the file.  I've made a change to only use the byte length of the combined MIDI chunks instead of the whole file length so this file should work now.  Release this in 2.0.8.  Thanks for sending,

-Garrett
