### ISSUE TITLE
[BUG] Loading file broken again...

### ISSUE THREAD

**Issue by TheAlienDrew** [grimmdude/MidiPlayerJS#58]
Not sure, but maybe it was caused by the fix to the older one? https://github.com/grimmdude/MidiPlayerJS/issues/57

Anyways, here's the new test, this file will break loading: [O-Zone_-_Dragostea_Din_Tei.mid](https://anonymousfiles.io/LGrb3QFk/)

**Comment by grimmdude** [comment]
Looks like this file has a bunch of sysex events and the library wasn't recognizing those properly.  I've pushed some changes to master which should fix that.  Going to try to address a couple other tickets and will publish a new release shortly.

-Garrett
