### ISSUE TITLE
Duration is calculated incorrectly for file

### ISSUE THREAD

**Issue by TheAlienDrew** [grimmdude/MidiPlayerJS#59]
When loading this file in VLC for example, it shows a time roughly about 2:56 (about 176 seconds) ... but loading it in the player, it shows a time of about 981.8 seconds... which is obviously incorrect.

Here's the file: [O-Zone_-_Dragostea_Din_Tei.mid](http://www.filedropper.com/o-zone-dragosteadintei)

**Comment by grimmdude** [comment]
Thanks @TheAlienDrew, this has been fixed in 2.0.10.

-Garrett
