### ISSUE TITLE
How to skip to a certain time in a midi track?

### ISSUE THREAD

**Issue by polyclick** [grimmdude/MidiPlayerJS#6]
I want to start playing at 00:10 seconds in. Is there a method to skip to a certain time? I see in the docs there's a startTime but can't seem to figure out how it works.

**Comment by grimmdude** [comment]
Hi @polyclick,

Thanks for your message.  I don't believe this functionality is implemented yet, but I think all of the logic is in place.  I will take a look at this this evening and see if I can get that going for you.

-Garrett

**Comment by grimmdude** [comment]
Hi @polyclick,

Whew that was a brain twister.  Had to rework a few things, which should hopefully optimize playback a bit.  I've added a few `skipTo` methods to the `Player` class which should be what you're looking for.  Let me know if you have any issues.

http://grimmdude.com/MidiPlayerJS/docs/Player.html#skipToSeconds

-Garrett

**Comment by polyclick** [comment]
Great thanks! I'm gonna try it out and let you know.

**Comment by grimmdude** [comment]
Cool, just a heads up you'll have to call `play()` after you skip.  So something like:

```js
Player.skipToSeconds(24).play();
```
