### ISSUE TITLE
Audio not playing from MidiWriterJS dataUri

### ISSUE THREAD

**Issue by leocaseiro** [grimmdude/MidiPlayerJS#91]
Hi there,

I've been exploring the usage of this library combined with the VexFlow integration based on MidiWriterJS, but the audio doesn't play.

Am I missing something, or is it broken?

https://codesandbox.io/s/vexflow-midiwriterjs-midiplayerjs-r3g4kw

(there is a button to play the audio, I can see the logs, but no audio is been played)

**Comment by grimmdude** [comment]
Hi @leocaseiro,

This library only fires the MIDI events at the appropriate time (what you're seeing in the logs).  In order to use them to trigger a sound you must use a soundfont library; something like https://github.com/gleitz/midi-js-soundfonts or similar.

**Comment by leocaseiro** [comment]
Thank you @grimmdude.

I finally understood why we need to integrate with sound-fount.

Here is a working example, if anyone is interested:

https://codesandbox.io/s/vexflow-midiwriterjs-midiplayerjs-soundfount-player-r3g4kw
