### ISSUE TITLE
Works fine with sample files, Cant load mid files from other locations

### ISSUE THREAD

**Issue by JanVeb** [grimmdude/MidiPlayerJS#92]
```
https://bitmidi.com/fur-elise-mid
https://www.midiworld.com/search/?q=classic
https://www.cprato.com/en/midi/download/164/aether-enzalla-elysia/Mi4xOTkwODYxMTI1NzU5RSsxNg==
```

Hi there, tried react demo and it works fine with mid files you have in your sample directory, but it doesn't play any other midi files I downloaded from these three websites.

I get this error
`Uncaught TypeError: Cannot read properties of undefined (reading 'play')
    at playNote (MidiReactPlayer.js:74:1)
    at MidiReactPlayer.js:106:1
    at index.browser.js:1272:1
    at Array.forEach (<anonymous>)
    at Player.triggerPlayerEvent (index.browser.js:1271:1)
    at Player.emitEvent (index.browser.js:1244:1)
    at Player.<anonymous> (index.browser.js:918:1)
    at Array.forEach (<anonymous>)
    at Player.playLoop (index.browser.js:887:1)`

**Comment by grimmdude** [comment]
Hi @JanVeb, this sounds like an issue with a different repository.  `MidiReactPlayer` isn't a file in this one.  Let me know if I'm misunderstanding though.

**Comment by JanVeb** [comment]
Oh I'm sorry, seems i opened this issue in wrong repository
