### ISSUE TITLE
How to find out the length on a note

### ISSUE THREAD

**Issue by urobot2011** [grimmdude/MidiPlayerJS#94]
How to find out the length on a note?
Is there a way to find out the length of a note in 'new MidiPlayer.Player(function)'?
I tried to solve the problem with [MIDI.js](https://github.com/mudcube/MIDI.js "https://github.com/mudcube/MIDI.js"). But I ran into a more serious problem.
Is there a way to find out the length of a note?

**Comment by Justiniscoding** [comment]
To see the length of a note, you use the `tick` value of the note on and off events. For example, the `tick` value for the note on event could be 100, and the value could be 200 for the note off event, which means that the note plays for 100 milliseconds (note off tick - note on tick)
